title: "Animal Crossing: New Horizons FAQ"
remote_theme: pmarsceill/just-the-docs
description: Fan-made FAQ for AC:NH
markdown: GFM
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"