title: "Animal Crossing: New Horizons FAQ"
<<<<<<< HEAD
remote_theme: pmarsceill/just-the-docs
=======
remote_theme: pdmosses/just-the-docs@callouts
>>>>>>> parent of 6af2c6b... dark mode
plugins:
  - jekyll-feed
  - jekyll-remote-theme
description: Fan-made FAQ for AC:NH
permalink: pretty #make url pretty
#logo: "https://chibisnorlax.github.io/acnhfaq/assets/logo_banner.png"
back_to_top: true
back_to_top_text: "Back to top" #add back to top as footer
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" #added this because back to top didn't show up without this, probably don't need it
search.button: true
kramdown:
  input: GFM
aux_links:
  "Toggle Theme":
    - "jtd.setTheme('dark');"